export const SET_CURRENT_SONG = 'SET_CURRENT_SONG'
export const SET_CURRENT_AMBIENCE = 'SET_CURRENT_AMBIENCE'

export const SET_POLYGONMASK = 'SET_POLYGONMASK'


export const TOGGLE_RANDOM = 'TOGGLE_RANDOM'
export const TOGGLE_REPEAT = 'TOGGLE_OPTIONS'
export const TOGGLE_PLAYING = 'TOGGLE_PLAYING'
export const TOGGLE_AMBIENCE_PLAYING = 'TOGGLE_AMBIENCE_PLAYING'
export const TOGGLE_AMBIENCE_AUDIO_GLOBAL = 'TOGGLE_AMBIENCE_AUDIO_GLOBAL'

export const SET_CLICKED = 'SET_CLICKED'

export const TOGGLE_SHOW_POLYGON = 'TOGGLE_SHOW_POLYGON'

