export const SET_CURRENT_SONG = 'SET_CURRENT_SONG'
export const SET_CURRENT_AMBIENCE = 'SET_CURRENT_AMBIENCE'

export const TOGGLE_RANDOM = 'TOGGLE_RANDOM'
export const TOGGLE_REPEAT = 'TOGGLE_OPTIONS'
export const TOGGLE_PLAYING = 'TOGGLE_PLAYING'
export const TOGGLE_AMBIENCE_PLAYING = 'TOGGLE_AMBIENCE_PLAYING'

export const SET_CLICKED = 'SET_CLICKED'



